Resources:
  EC2WithOneSG:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 'ami-0470e33cd681b2476'
      InstanceType: t2.micro
      SecurityGroups:
        - default
        - !Ref NewSecurityGroup

  NewSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: New SecurityGroup
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0