Resources:
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 'ami-0470e33cd681b2476'
      InstanceType: t2.micro
      KeyName: manman-new-keypair
      SecurityGroups:
        - default
        - !Ref NewSG

  NewSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecrityGroup with two variations
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0