Parameters:
  ParamInstanceType:
    Type: String
    Description: Instance Type Parameter
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.nano
      - m2.nano

  ParamAvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: AvailabilityZone Parameter

  ParamKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: KeyName Parameter

Resources:
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 'ami-0470e33cd681b2476'
      InstanceType:
        Ref: ParamInstanceType
      KeyName:
        Ref: ParamKeyName
      AvailabilityZone:
        Ref: ParamAvailabilityZone
      SecurityGroups:
        - !Ref NewSecurityGroup

  NewSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: New SecurityGroup
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyEC2