Mappings:
  ImageIdMapping:
    ap-south-1:
      LINUX2AMI: ami-0470e33cd681b2476
    us-east-1:
      LINUX2AMI: ami-0323c3dd2da7fb37d
    us-east-2:
      LINUX2AMI: ami-0f7919c33c90f5b58

Resources:
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - ImageIdMapping
        - !Ref 'AWS::Region'
        - LINUX2AMI
      InstanceType: t2.micro
      SecurityGroups:
        - default